<?php echo $this->doctype() ?>
<html lang="pt-br">
 	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap.min.css')
									->appendStylesheet($this->baseUrl().'/css/style.css');
		?>
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
		        <div class="navbar-header">
		          <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
		            <span class="sr-only">Alternar navegação</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		          </button>
		          <a href="/" class="navbar-brand">ZF Quickstart</a>
		        </div>
		        <div class="navbar-collapse collapse" style="height: 1px;">
		          <ul class="nav navbar-nav">
		            <li><a href="<?php echo $this->url(array('module' => 'guestbook', 'controller'=>'guestbook'), 'default', true) ?>">Guestbook</a></li>
		            <li><a href="<?php echo $this->url(array('module' => 'album', 'controller'=>'album'), 'default', true) ?>">Album</a></li>
		          </ul>
		        </div><!--/.nav-collapse -->
			</div>
		</div>
		
		<div id="content">
			<?php echo $this->layout()->content ?>
		</div>
		
		<?php
			echo $this->headScript()->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js')
									->appendFile('/js/bootstrap.min.js');
		?>
	</body>
</html>
