<?php
$this->title = "Adicionar album";
$this->headTitle($this->title);
?>
<div class="container">
	<span>Por favor, preencha o formulário abaixo para adicionar um novo album</span>
	<form method="<?php echo $this->form->getMethod() ?>" action="<?php echo $this->form->getAction()?>">
		<?php $this->form->setAction($this->url()); ?>
		
		<?php echo $this->form->title->renderLabel(); ?>
		<?php echo $this->formText('title', '', array('class' => 'form-control')); ?>
		<?php echo $this->form->title->renderErrors(); ?>
		
		<?php echo $this->form->artist->renderLabel(); ?>
		<?php echo $this->formText('artist', '', array('class' => 'form-control')); ?>
		<?php echo $this->form->artist->renderErrors(); ?>
		
		<?php echo $this->form->captcha; ?>
		
		<?php echo $this->form->submit; ?>
		
		<?php echo $this->form->csrf; ?>
	</form>
</div>


