<?php
$this->title = "Remover album";
$this->headTitle($this->title);
?>
<div class="container">
	<p>Tem certeza que deseja remover o album
	'<?php echo $this->escape($this->album['title']); ?>' do
	'<?php echo $this->escape($this->album['artist']); ?>'?
	</p>
	<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
		<div>
		<input type="hidden" name="id" value="<?php echo $this->album['id']; ?>" />
		<input type="submit" name="del" value="Yes" />
		<input type="submit" name="del" value="No" />
		</div>
	</form>
</div>


