<?php
$this->title = "Meus albuns";
$this->headTitle($this->title);
?>
<div class="container">
	<p><a class="btn btn-large btn-success" href="<?php echo $this->url(array('module' => 'album', 'controller'=>'album','action'=>'add'));?>">Add novo album</a></p>
	<div class="table-responsive">
		<table class="table">
			<thead>     
				<tr>
					<th>Title</th>
					<th>Artist</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->entries as $album) : ?>
				<tr>
					<td><?php echo $this->escape($album->title);?></td>
					<td><?php echo $this->escape($album->artist);?></td>
					<td>
						<a class="btn btn-xs btn-warning" href="<?php echo $this->url(array('module' => 'album', 'controller'=>'album', 'action'=>'edit', 'id'=>$album->id));?>"><span class="glyphicon glyphicon-edit"></span></a>
						<a class="btn btn-xs btn-danger" href="<?php echo $this->url(array('module' => 'album', 'controller'=>'album', 'action'=>'delete', 'id'=>$album->id));?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
					</td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>
